eureka:
  client:
    fetch-registry: true
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
   
  instance:
    healthCheckUrlPath: /salesforce/health
    leaseExpirationDurationInSeconds: 2
    leaseRenewalIntervalInSeconds: 1
    statusPageUrlPath: /salesforce/info
logging:
  level:
    org:
      springframework:
        boot:
          context:
            web:
              ErrorPageFilter: 'off'
security:
  basic:
    enabled: false
server:
  error:
    whitelabel:
      enabled: true
  servlet-path: /salesforce
spring:
  application:
    name: salesforce-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/portal?useSSL=false
    username: root
  jmx:
    default-domain: salesforce-service
  profiles:
    active: prod
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
