package com.nmims.helpers;

public class WebExMeetingManager1 {
	
	private String requestXML =  "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>"
			+ "<serv:message xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
			+ " xmlns:serv=\"http://www.webex.com/schemas/2002/06/service\""
			+ "		xsi:schemaLocation=\"http://www.webex.com/schemas/2002/06/service\">"
			+ "	<header>"
			+ "		<securityContext>"
			+ "			<webExID>hostid</webExID>"
			+ "			<password>hostpassword</password>"
			+ "			<siteID>0000</siteID>"
			+ "			<partnerID>9999</partnerID>"
			+ "			<email>johnsmith@xyz.com</email>"
			+ "		</securityContext>"
			+ "	</header>"
			+ "	<body>"
			+ "		<bodyContent xsi:type=\"java:com.webex.service.binding.training.CreateTrainingSession\">"
			+ "			<accessControl>"
			+ "				<listing>PUBLIC</listing>"
			+ "				<sessionPassword>111111</sessionPassword>"
			+ "			</accessControl>"
			+ "			<schedule>"
			+ "				<startDate>4/05/2004 10:00:00</startDate>"
			+ "				<timeZone>GMT-12:00, Dateline (Eniwetok)</timeZone>"
			+ "				<duration>60</duration>"
			+ "				<timeZoneID>46</timeZoneID>"
			+ "				<openTime>20</openTime>"
			+ "			</schedule>"
			+ "			<metaData>"
			+ "				<confName>jimz hol test</confName>"
			+ "				<agenda>agenda 1</agenda>"
			+ "				<description>description</description>"
			+ "				<greeting>greeting</greeting>"
			+ "				<location>location</location>"
			+ "				<invitation>invitation</invitation>"
			+ "			</metaData>"
			+ "			<enableOptions>"
			+ "				<attendeeList>false</attendeeList>"
			+ "				<javaClient>false</javaClient>"
			+ "				<nativeClient>true</nativeClient>"
			+ "				<chat>false</chat>"
			+ "				<poll>false</poll>"
			+ "				<audioVideo>false</audioVideo>"
			+ "				<fileShare>false</fileShare>"
			+ "				<presentation>false</presentation>"
			+ "				<applicationShare>false</applicationShare>"
			+ "				<desktopShare>false</desktopShare>"
			+ "				<webTour>false</webTour>"
			+ "				<trainingSessionRecord>false</trainingSessionRecord>"
			+ "				<annotation>false</annotation>"
			+ "				<importDocument>false</importDocument>"
			+ "				<saveDocument>false</saveDocument>"
			+ "				<printDocument>false</printDocument>"
			+ "				<pointer>false</pointer>"
			+ "				<switchPage>false</switchPage>"
			+ "				<fullScreen>false</fullScreen>"
			+ "				<thumbnail>false</thumbnail>"
			+ "				<zoom>false</zoom>"
			+ "				<copyPage>false</copyPage>"
			+ "				<rcAppShare>false</rcAppShare>"
			+ "				<rcDesktopShare>false</rcDesktopShare>"
			+ "				<rcWebTour>false</rcWebTour>"
			+ "				<attendeeRecordTrainingSession>false"
			+ "				</attendeeRecordTrainingSession>"
			+ "				<voip>false</voip>"
			+ "				<faxIntoTrainingSession>false</faxIntoTrainingSession>"
			+ "				<autoDeleteAfterMeetingEnd>true</autoDeleteAfterMeetingEnd>"
			+ "			</enableOptions>"
			+ "			<telephony>"
			+ "				<telephonySupport>NONE</telephonySupport>"
			+ "				<numPhoneLines>4</numPhoneLines>"
			+ "				<extTelephonyURL>String</extTelephonyURL>"
			+ "				<extTelephonyDescription>String</extTelephonyDescription>"
			+ "				<enableTSP>false</enableTSP>"
			+ "				<tspAccountIndex>1</tspAccountIndex>"
			+ "			</telephony>"

			+ "		</bodyContent>"
			+ "	</body>"
			+ "</serv:message>";
	

}
