
package com.nmims.webservice.fedex.track;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TrackPortType", targetNamespace = "http://fedex.com/ws/track/v10")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TrackPortType {


    /**
     * 
     * @param signatureProofOfDeliveryLetterRequest
     * @return
     *     returns com.nmims.webservice.fedex.track.SignatureProofOfDeliveryLetterReply
     */
    @WebMethod(action = "http://fedex.com/ws/track/v10/retrieveSignatureProofOfDeliveryLetter")
    @WebResult(name = "SignatureProofOfDeliveryLetterReply", targetNamespace = "http://fedex.com/ws/track/v10", partName = "SignatureProofOfDeliveryLetterReply")
    public SignatureProofOfDeliveryLetterReply retrieveSignatureProofOfDeliveryLetter(
        @WebParam(name = "SignatureProofOfDeliveryLetterRequest", targetNamespace = "http://fedex.com/ws/track/v10", partName = "SignatureProofOfDeliveryLetterRequest")
        SignatureProofOfDeliveryLetterRequest signatureProofOfDeliveryLetterRequest);

    /**
     * 
     * @param trackRequest
     * @return
     *     returns com.nmims.webservice.fedex.track.TrackReply
     */
    @WebMethod(action = "http://fedex.com/ws/track/v10/track")
    @WebResult(name = "TrackReply", targetNamespace = "http://fedex.com/ws/track/v10", partName = "TrackReply")
    public TrackReply track(
        @WebParam(name = "TrackRequest", targetNamespace = "http://fedex.com/ws/track/v10", partName = "TrackRequest")
        TrackRequest trackRequest);

    /**
     * 
     * @param signatureProofOfDeliveryFaxRequest
     * @return
     *     returns com.nmims.webservice.fedex.track.SignatureProofOfDeliveryFaxReply
     */
    @WebMethod(action = "http://fedex.com/ws/track/v10/sendSignatureProofOfDeliveryFax")
    @WebResult(name = "SignatureProofOfDeliveryFaxReply", targetNamespace = "http://fedex.com/ws/track/v10", partName = "SignatureProofOfDeliveryFaxReply")
    public SignatureProofOfDeliveryFaxReply sendSignatureProofOfDeliveryFax(
        @WebParam(name = "SignatureProofOfDeliveryFaxRequest", targetNamespace = "http://fedex.com/ws/track/v10", partName = "SignatureProofOfDeliveryFaxRequest")
        SignatureProofOfDeliveryFaxRequest signatureProofOfDeliveryFaxRequest);

    /**
     * 
     * @param sendNotificationsRequest
     * @return
     *     returns com.nmims.webservice.fedex.track.SendNotificationsReply
     */
    @WebMethod(action = "http://fedex.com/ws/track/v10/sendNotifications")
    @WebResult(name = "SendNotificationsReply", targetNamespace = "http://fedex.com/ws/track/v10", partName = "SendNotificationsReply")
    public SendNotificationsReply sendNotifications(
        @WebParam(name = "SendNotificationsRequest", targetNamespace = "http://fedex.com/ws/track/v10", partName = "SendNotificationsRequest")
        SendNotificationsRequest sendNotificationsRequest);

}
